# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xinwen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
